//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace KShiftSmartPortal.Database
{

    public partial class SCM_WORK_ORDER_DETAIL : XPLiteObject
    {
        string fCUSTOMER_NO;
        [DbType("VARCHAR2(32 BYTE)")]
        public string CUSTOMER_NO
        {
            get { return fCUSTOMER_NO; }
            set { SetPropertyValue<string>(nameof(CUSTOMER_NO), ref fCUSTOMER_NO, value); }
        }
        string fC_UNIT_PRICE_NO;
        [DbType("VARCHAR2(12 BYTE)")]
        public string C_UNIT_PRICE_NO
        {
            get { return fC_UNIT_PRICE_NO; }
            set { SetPropertyValue<string>(nameof(C_UNIT_PRICE_NO), ref fC_UNIT_PRICE_NO, value); }
        }
        decimal fCUSTOMER_PRICE;
        public decimal CUSTOMER_PRICE
        {
            get { return fCUSTOMER_PRICE; }
            set { SetPropertyValue<decimal>(nameof(CUSTOMER_PRICE), ref fCUSTOMER_PRICE, value); }
        }
        decimal fREQ_C_PRICE_RATIO;
        public decimal REQ_C_PRICE_RATIO
        {
            get { return fREQ_C_PRICE_RATIO; }
            set { SetPropertyValue<decimal>(nameof(REQ_C_PRICE_RATIO), ref fREQ_C_PRICE_RATIO, value); }
        }
        decimal fREQ_CUSTOMER_PRICE;
        public decimal REQ_CUSTOMER_PRICE
        {
            get { return fREQ_CUSTOMER_PRICE; }
            set { SetPropertyValue<decimal>(nameof(REQ_CUSTOMER_PRICE), ref fREQ_CUSTOMER_PRICE, value); }
        }
        string fPARTNER_NO;
        [DbType("VARCHAR2(32 BYTE)")]
        public string PARTNER_NO
        {
            get { return fPARTNER_NO; }
            set { SetPropertyValue<string>(nameof(PARTNER_NO), ref fPARTNER_NO, value); }
        }
        string fP_UNIT_PRICE_NO;
        [DbType("VARCHAR2(12 BYTE)")]
        public string P_UNIT_PRICE_NO
        {
            get { return fP_UNIT_PRICE_NO; }
            set { SetPropertyValue<string>(nameof(P_UNIT_PRICE_NO), ref fP_UNIT_PRICE_NO, value); }
        }
        decimal fPARTNER_PRICE;
        public decimal PARTNER_PRICE
        {
            get { return fPARTNER_PRICE; }
            set { SetPropertyValue<decimal>(nameof(PARTNER_PRICE), ref fPARTNER_PRICE, value); }
        }
        decimal fREQ_P_PRICE_RATIO;
        public decimal REQ_P_PRICE_RATIO
        {
            get { return fREQ_P_PRICE_RATIO; }
            set { SetPropertyValue<decimal>(nameof(REQ_P_PRICE_RATIO), ref fREQ_P_PRICE_RATIO, value); }
        }
        decimal fREQ_PARTNER_PRICE;
        public decimal REQ_PARTNER_PRICE
        {
            get { return fREQ_PARTNER_PRICE; }
            set { SetPropertyValue<decimal>(nameof(REQ_PARTNER_PRICE), ref fREQ_PARTNER_PRICE, value); }
        }
        string fAPPROVAL_USER_ID;
        [DbType("VARCHAR2(32 BYTE)")]
        public string APPROVAL_USER_ID
        {
            get { return fAPPROVAL_USER_ID; }
            set { SetPropertyValue<string>(nameof(APPROVAL_USER_ID), ref fAPPROVAL_USER_ID, value); }
        }
        DateTime fAPPROVAL_REQUEST_DATE;
        public DateTime APPROVAL_REQUEST_DATE
        {
            get { return fAPPROVAL_REQUEST_DATE; }
            set { SetPropertyValue<DateTime>(nameof(APPROVAL_REQUEST_DATE), ref fAPPROVAL_REQUEST_DATE, value); }
        }
        DateTime fAPPROVAL_DATE;
        public DateTime APPROVAL_DATE
        {
            get { return fAPPROVAL_DATE; }
            set { SetPropertyValue<DateTime>(nameof(APPROVAL_DATE), ref fAPPROVAL_DATE, value); }
        }
        string fIN_USER;
        [DbType("VARCHAR2(20 BYTE)")]
        public string IN_USER
        {
            get { return fIN_USER; }
            set { SetPropertyValue<string>(nameof(IN_USER), ref fIN_USER, value); }
        }
        DateTime fIN_DATE;
        [ColumnDbDefaultValue("SYSDATE")]
        public DateTime IN_DATE
        {
            get { return fIN_DATE; }
            set { SetPropertyValue<DateTime>(nameof(IN_DATE), ref fIN_DATE, value); }
        }
        string fIN_IP;
        [DbType("VARCHAR2(15 BYTE)")]
        public string IN_IP
        {
            get { return fIN_IP; }
            set { SetPropertyValue<string>(nameof(IN_IP), ref fIN_IP, value); }
        }
        string fIN_PID;
        [DbType("VARCHAR2(50 BYTE)")]
        public string IN_PID
        {
            get { return fIN_PID; }
            set { SetPropertyValue<string>(nameof(IN_PID), ref fIN_PID, value); }
        }
        string fUP_USER;
        [DbType("VARCHAR2(20 BYTE)")]
        public string UP_USER
        {
            get { return fUP_USER; }
            set { SetPropertyValue<string>(nameof(UP_USER), ref fUP_USER, value); }
        }
        DateTime fUP_DATE;
        public DateTime UP_DATE
        {
            get { return fUP_DATE; }
            set { SetPropertyValue<DateTime>(nameof(UP_DATE), ref fUP_DATE, value); }
        }
        string fUP_IP;
        [DbType("VARCHAR2(15 BYTE)")]
        public string UP_IP
        {
            get { return fUP_IP; }
            set { SetPropertyValue<string>(nameof(UP_IP), ref fUP_IP, value); }
        }
        string fUP_PID;
        [DbType("VARCHAR2(50 BYTE)")]
        public string UP_PID
        {
            get { return fUP_PID; }
            set { SetPropertyValue<string>(nameof(UP_PID), ref fUP_PID, value); }
        }
        public struct CompoundKey1Struct
        {
            [DbType("VARCHAR2(128 BYTE)")]
            [Persistent("COMPANY_NO")]
            public string COMPANY_NO { get; set; }
            [DbType("VARCHAR2(12 BYTE)")]
            [Persistent("CASE_NO")]
            public string CASE_NO { get; set; }
            [DbType("VARCHAR2(32 BYTE)")]
            [Persistent("PROJECT_NO")]
            public string PROJECT_NO { get; set; }
            [DbType("VARCHAR2(32 BYTE)")]
            [Persistent("ORDER_NO")]
            public string ORDER_NO { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
