//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;

namespace KShiftSmartPortal.Database
{

    public partial class SCM_CASE_MASTER : XPLiteObject
    {
        decimal fVAL06;
        public decimal VAL06
        {
            get { return fVAL06; }
            set { SetPropertyValue<decimal>(nameof(VAL06), ref fVAL06, value); }
        }
        decimal fVAL07;
        public decimal VAL07
        {
            get { return fVAL07; }
            set { SetPropertyValue<decimal>(nameof(VAL07), ref fVAL07, value); }
        }
        decimal fVAL08;
        public decimal VAL08
        {
            get { return fVAL08; }
            set { SetPropertyValue<decimal>(nameof(VAL08), ref fVAL08, value); }
        }
        decimal fVAL09;
        public decimal VAL09
        {
            get { return fVAL09; }
            set { SetPropertyValue<decimal>(nameof(VAL09), ref fVAL09, value); }
        }
        decimal fVAL10;
        public decimal VAL10
        {
            get { return fVAL10; }
            set { SetPropertyValue<decimal>(nameof(VAL10), ref fVAL10, value); }
        }
        decimal fVAL01;
        public decimal VAL01
        {
            get { return fVAL01; }
            set { SetPropertyValue<decimal>(nameof(VAL01), ref fVAL01, value); }
        }
        decimal fVAL02;
        public decimal VAL02
        {
            get { return fVAL02; }
            set { SetPropertyValue<decimal>(nameof(VAL02), ref fVAL02, value); }
        }
        decimal fVAL03;
        public decimal VAL03
        {
            get { return fVAL03; }
            set { SetPropertyValue<decimal>(nameof(VAL03), ref fVAL03, value); }
        }
        decimal fVAL04;
        public decimal VAL04
        {
            get { return fVAL04; }
            set { SetPropertyValue<decimal>(nameof(VAL04), ref fVAL04, value); }
        }
        decimal fVAL05;
        public decimal VAL05
        {
            get { return fVAL05; }
            set { SetPropertyValue<decimal>(nameof(VAL05), ref fVAL05, value); }
        }
        string fPROP1;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP1
        {
            get { return fPROP1; }
            set { SetPropertyValue<string>(nameof(PROP1), ref fPROP1, value); }
        }
        string fPROP2;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP2
        {
            get { return fPROP2; }
            set { SetPropertyValue<string>(nameof(PROP2), ref fPROP2, value); }
        }
        string fPROP3;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP3
        {
            get { return fPROP3; }
            set { SetPropertyValue<string>(nameof(PROP3), ref fPROP3, value); }
        }
        string fPROP4;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP4
        {
            get { return fPROP4; }
            set { SetPropertyValue<string>(nameof(PROP4), ref fPROP4, value); }
        }
        string fPROP5;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP5
        {
            get { return fPROP5; }
            set { SetPropertyValue<string>(nameof(PROP5), ref fPROP5, value); }
        }
        string fPROP6;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP6
        {
            get { return fPROP6; }
            set { SetPropertyValue<string>(nameof(PROP6), ref fPROP6, value); }
        }
        string fPROP7;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP7
        {
            get { return fPROP7; }
            set { SetPropertyValue<string>(nameof(PROP7), ref fPROP7, value); }
        }
        string fPROP8;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP8
        {
            get { return fPROP8; }
            set { SetPropertyValue<string>(nameof(PROP8), ref fPROP8, value); }
        }
        string fPROP9;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP9
        {
            get { return fPROP9; }
            set { SetPropertyValue<string>(nameof(PROP9), ref fPROP9, value); }
        }
        string fIN_USER;
        [DbType("VARCHAR2(20 BYTE)")]
        public string IN_USER
        {
            get { return fIN_USER; }
            set { SetPropertyValue<string>(nameof(IN_USER), ref fIN_USER, value); }
        }
        DateTime fIN_DATE;
        [ColumnDbDefaultValue("SYSDATE")]
        public DateTime IN_DATE
        {
            get { return fIN_DATE; }
            set { SetPropertyValue<DateTime>(nameof(IN_DATE), ref fIN_DATE, value); }
        }
        string fIN_IP;
        [DbType("VARCHAR2(15 BYTE)")]
        public string IN_IP
        {
            get { return fIN_IP; }
            set { SetPropertyValue<string>(nameof(IN_IP), ref fIN_IP, value); }
        }
        string fIN_PID;
        [DbType("VARCHAR2(50 BYTE)")]
        public string IN_PID
        {
            get { return fIN_PID; }
            set { SetPropertyValue<string>(nameof(IN_PID), ref fIN_PID, value); }
        }
        string fUP_USER;
        [DbType("VARCHAR2(20 BYTE)")]
        public string UP_USER
        {
            get { return fUP_USER; }
            set { SetPropertyValue<string>(nameof(UP_USER), ref fUP_USER, value); }
        }
        DateTime fUP_DATE;
        public DateTime UP_DATE
        {
            get { return fUP_DATE; }
            set { SetPropertyValue<DateTime>(nameof(UP_DATE), ref fUP_DATE, value); }
        }
        string fUP_IP;
        [DbType("VARCHAR2(15 BYTE)")]
        public string UP_IP
        {
            get { return fUP_IP; }
            set { SetPropertyValue<string>(nameof(UP_IP), ref fUP_IP, value); }
        }
        string fUP_PID;
        [DbType("VARCHAR2(50 BYTE)")]
        public string UP_PID
        {
            get { return fUP_PID; }
            set { SetPropertyValue<string>(nameof(UP_PID), ref fUP_PID, value); }
        }
        string fCASE_TYPE;
        [ColumnDbDefaultValue("'SIM'                 ")]
        [DbType("VARCHAR2(12 BYTE)")]
        public string CASE_TYPE
        {
            get { return fCASE_TYPE; }
            set { SetPropertyValue<string>(nameof(CASE_TYPE), ref fCASE_TYPE, value); }
        }
        string fCASE_NAME;
        [DbType("VARCHAR2(64 BYTE)")]
        public string CASE_NAME
        {
            get { return fCASE_NAME; }
            set { SetPropertyValue<string>(nameof(CASE_NAME), ref fCASE_NAME, value); }
        }
        string fCASE_STATUS;
        [ColumnDbDefaultValue("'WORKING'")]
        [DbType("VARCHAR2(12 BYTE)")]
        public string CASE_STATUS
        {
            get { return fCASE_STATUS; }
            set { SetPropertyValue<string>(nameof(CASE_STATUS), ref fCASE_STATUS, value); }
        }
        DateTime fAPPST_DT;
        public DateTime APPST_DT
        {
            get { return fAPPST_DT; }
            set { SetPropertyValue<DateTime>(nameof(APPST_DT), ref fAPPST_DT, value); }
        }
        DateTime fAPPFI_DT;
        public DateTime APPFI_DT
        {
            get { return fAPPFI_DT; }
            set { SetPropertyValue<DateTime>(nameof(APPFI_DT), ref fAPPFI_DT, value); }
        }
        int fVIEW_ORDER;
        public int VIEW_ORDER
        {
            get { return fVIEW_ORDER; }
            set { SetPropertyValue<int>(nameof(VIEW_ORDER), ref fVIEW_ORDER, value); }
        }
        string fUSE_YN;
        [DbType("VARCHAR2(1 BYTE)")]
        public string USE_YN
        {
            get { return fUSE_YN; }
            set { SetPropertyValue<string>(nameof(USE_YN), ref fUSE_YN, value); }
        }
        string fRMK;
        [DbType("VARCHAR2(128 BYTE)")]
        public string RMK
        {
            get { return fRMK; }
            set { SetPropertyValue<string>(nameof(RMK), ref fRMK, value); }
        }
        string fTAG1;
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG1
        {
            get { return fTAG1; }
            set { SetPropertyValue<string>(nameof(TAG1), ref fTAG1, value); }
        }
        string fTAG2;
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG2
        {
            get { return fTAG2; }
            set { SetPropertyValue<string>(nameof(TAG2), ref fTAG2, value); }
        }
        string fTAG3;
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG3
        {
            get { return fTAG3; }
            set { SetPropertyValue<string>(nameof(TAG3), ref fTAG3, value); }
        }
        string fTAG4;
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG4
        {
            get { return fTAG4; }
            set { SetPropertyValue<string>(nameof(TAG4), ref fTAG4, value); }
        }
        string fTAG5;
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG5
        {
            get { return fTAG5; }
            set { SetPropertyValue<string>(nameof(TAG5), ref fTAG5, value); }
        }
        public struct CompoundKey1Struct
        {
            [DbType("VARCHAR2(12 BYTE)")]
            [Persistent("CASE_NO")]
            public string CASE_NO { get; set; }
            [DbType("VARCHAR2(128 BYTE)")]
            [Persistent("COMPANY_NO")]
            public string COMPANY_NO { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
