//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace KShiftSmartPortal.Database
{

    public partial class SCM_WORK_ORDER_MASTER : XPLiteObject
    {
        string fORDER_NAME;
        [DbType("VARCHAR2(128 BYTE)")]
        public string ORDER_NAME
        {
            get { return fORDER_NAME; }
            set { SetPropertyValue<string>(nameof(ORDER_NAME), ref fORDER_NAME, value); }
        }
        string fWORK_LIST;
        [DbType("VARCHAR2(256 BYTE)")]
        public string WORK_LIST
        {
            get { return fWORK_LIST; }
            set { SetPropertyValue<string>(nameof(WORK_LIST), ref fWORK_LIST, value); }
        }
        string fACT_NO;
        [DbType("VARCHAR2(32 BYTE)")]
        public string ACT_NO
        {
            get { return fACT_NO; }
            set { SetPropertyValue<string>(nameof(ACT_NO), ref fACT_NO, value); }
        }
        string fSUB_ACT_NO;
        [DbType("VARCHAR2(32 BYTE)")]
        public string SUB_ACT_NO
        {
            get { return fSUB_ACT_NO; }
            set { SetPropertyValue<string>(nameof(SUB_ACT_NO), ref fSUB_ACT_NO, value); }
        }
        string fITEM_NO;
        [DbType("VARCHAR2(12 BYTE)")]
        public string ITEM_NO
        {
            get { return fITEM_NO; }
            set { SetPropertyValue<string>(nameof(ITEM_NO), ref fITEM_NO, value); }
        }
        string fORG_NO;
        [DbType("VARCHAR2(128 BYTE)")]
        public string ORG_NO
        {
            get { return fORG_NO; }
            set { SetPropertyValue<string>(nameof(ORG_NO), ref fORG_NO, value); }
        }
        string fRESOURCE_NO;
        [DbType("VARCHAR2(12 BYTE)")]
        public string RESOURCE_NO
        {
            get { return fRESOURCE_NO; }
            set { SetPropertyValue<string>(nameof(RESOURCE_NO), ref fRESOURCE_NO, value); }
        }
        string fEMP_NO;
        [DbType("VARCHAR2(32 BYTE)")]
        public string EMP_NO
        {
            get { return fEMP_NO; }
            set { SetPropertyValue<string>(nameof(EMP_NO), ref fEMP_NO, value); }
        }
        DateTime fWORK_ST;
        public DateTime WORK_ST
        {
            get { return fWORK_ST; }
            set { SetPropertyValue<DateTime>(nameof(WORK_ST), ref fWORK_ST, value); }
        }
        DateTime fWORK_FI;
        public DateTime WORK_FI
        {
            get { return fWORK_FI; }
            set { SetPropertyValue<DateTime>(nameof(WORK_FI), ref fWORK_FI, value); }
        }
        DateTime fDUE_DATE;
        public DateTime DUE_DATE
        {
            get { return fDUE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(DUE_DATE), ref fDUE_DATE, value); }
        }
        DateTime fCOMP_DATE;
        public DateTime COMP_DATE
        {
            get { return fCOMP_DATE; }
            set { SetPropertyValue<DateTime>(nameof(COMP_DATE), ref fCOMP_DATE, value); }
        }
        DateTime fQM_DATE;
        public DateTime QM_DATE
        {
            get { return fQM_DATE; }
            set { SetPropertyValue<DateTime>(nameof(QM_DATE), ref fQM_DATE, value); }
        }
        DateTime fQM_COMP_DATE;
        public DateTime QM_COMP_DATE
        {
            get { return fQM_COMP_DATE; }
            set { SetPropertyValue<DateTime>(nameof(QM_COMP_DATE), ref fQM_COMP_DATE, value); }
        }
        int fREV_NO;
        public int REV_NO
        {
            get { return fREV_NO; }
            set { SetPropertyValue<int>(nameof(REV_NO), ref fREV_NO, value); }
        }
        string fWORK_STAGE;
        [DbType("VARCHAR2(32 BYTE)")]
        public string WORK_STAGE
        {
            get { return fWORK_STAGE; }
            set { SetPropertyValue<string>(nameof(WORK_STAGE), ref fWORK_STAGE, value); }
        }
        string fWORK_STAGE_DET;
        [DbType("VARCHAR2(32 BYTE)")]
        public string WORK_STAGE_DET
        {
            get { return fWORK_STAGE_DET; }
            set { SetPropertyValue<string>(nameof(WORK_STAGE_DET), ref fWORK_STAGE_DET, value); }
        }
        decimal fPLAN_MHR;
        public decimal PLAN_MHR
        {
            get { return fPLAN_MHR; }
            set { SetPropertyValue<decimal>(nameof(PLAN_MHR), ref fPLAN_MHR, value); }
        }
        decimal fREAL_MHR;
        public decimal REAL_MHR
        {
            get { return fREAL_MHR; }
            set { SetPropertyValue<decimal>(nameof(REAL_MHR), ref fREAL_MHR, value); }
        }
        decimal fPLAN_MP;
        public decimal PLAN_MP
        {
            get { return fPLAN_MP; }
            set { SetPropertyValue<decimal>(nameof(PLAN_MP), ref fPLAN_MP, value); }
        }
        decimal fREAL_MP;
        public decimal REAL_MP
        {
            get { return fREAL_MP; }
            set { SetPropertyValue<decimal>(nameof(REAL_MP), ref fREAL_MP, value); }
        }
        string fRMK;
        [DbType("VARCHAR2(128 BYTE)")]
        public string RMK
        {
            get { return fRMK; }
            set { SetPropertyValue<string>(nameof(RMK), ref fRMK, value); }
        }
        decimal fVAL01;
        public decimal VAL01
        {
            get { return fVAL01; }
            set { SetPropertyValue<decimal>(nameof(VAL01), ref fVAL01, value); }
        }
        decimal fVAL02;
        public decimal VAL02
        {
            get { return fVAL02; }
            set { SetPropertyValue<decimal>(nameof(VAL02), ref fVAL02, value); }
        }
        decimal fVAL03;
        public decimal VAL03
        {
            get { return fVAL03; }
            set { SetPropertyValue<decimal>(nameof(VAL03), ref fVAL03, value); }
        }
        decimal fVAL04;
        public decimal VAL04
        {
            get { return fVAL04; }
            set { SetPropertyValue<decimal>(nameof(VAL04), ref fVAL04, value); }
        }
        decimal fVAL05;
        public decimal VAL05
        {
            get { return fVAL05; }
            set { SetPropertyValue<decimal>(nameof(VAL05), ref fVAL05, value); }
        }
        decimal fVAL06;
        public decimal VAL06
        {
            get { return fVAL06; }
            set { SetPropertyValue<decimal>(nameof(VAL06), ref fVAL06, value); }
        }
        decimal fVAL07;
        public decimal VAL07
        {
            get { return fVAL07; }
            set { SetPropertyValue<decimal>(nameof(VAL07), ref fVAL07, value); }
        }
        decimal fVAL08;
        public decimal VAL08
        {
            get { return fVAL08; }
            set { SetPropertyValue<decimal>(nameof(VAL08), ref fVAL08, value); }
        }
        decimal fVAL09;
        public decimal VAL09
        {
            get { return fVAL09; }
            set { SetPropertyValue<decimal>(nameof(VAL09), ref fVAL09, value); }
        }
        decimal fVAL10;
        public decimal VAL10
        {
            get { return fVAL10; }
            set { SetPropertyValue<decimal>(nameof(VAL10), ref fVAL10, value); }
        }
        string fTAG1;
        [DbType("VARCHAR2(64 BYTE)")]
        public string TAG1
        {
            get { return fTAG1; }
            set { SetPropertyValue<string>(nameof(TAG1), ref fTAG1, value); }
        }
        string fTAG2;
        [DbType("VARCHAR2(64 BYTE)")]
        public string TAG2
        {
            get { return fTAG2; }
            set { SetPropertyValue<string>(nameof(TAG2), ref fTAG2, value); }
        }
        string fTAG3;
        [DbType("VARCHAR2(64 BYTE)")]
        public string TAG3
        {
            get { return fTAG3; }
            set { SetPropertyValue<string>(nameof(TAG3), ref fTAG3, value); }
        }
        string fTAG4;
        [DbType("VARCHAR2(64 BYTE)")]
        public string TAG4
        {
            get { return fTAG4; }
            set { SetPropertyValue<string>(nameof(TAG4), ref fTAG4, value); }
        }
        string fTAG5;
        [DbType("VARCHAR2(64 BYTE)")]
        public string TAG5
        {
            get { return fTAG5; }
            set { SetPropertyValue<string>(nameof(TAG5), ref fTAG5, value); }
        }
        string fPROP01;
        [DbType("VARCHAR2(256 BYTE)")]
        public string PROP01
        {
            get { return fPROP01; }
            set { SetPropertyValue<string>(nameof(PROP01), ref fPROP01, value); }
        }
        string fPROP02;
        [DbType("VARCHAR2(256 BYTE)")]
        public string PROP02
        {
            get { return fPROP02; }
            set { SetPropertyValue<string>(nameof(PROP02), ref fPROP02, value); }
        }
        string fPROP03;
        [DbType("VARCHAR2(64 BYTE)")]
        public string PROP03
        {
            get { return fPROP03; }
            set { SetPropertyValue<string>(nameof(PROP03), ref fPROP03, value); }
        }
        string fPROP04;
        [DbType("VARCHAR2(64 BYTE)")]
        public string PROP04
        {
            get { return fPROP04; }
            set { SetPropertyValue<string>(nameof(PROP04), ref fPROP04, value); }
        }
        string fPROP05;
        [DbType("VARCHAR2(64 BYTE)")]
        public string PROP05
        {
            get { return fPROP05; }
            set { SetPropertyValue<string>(nameof(PROP05), ref fPROP05, value); }
        }
        string fPROP06;
        [DbType("VARCHAR2(64 BYTE)")]
        public string PROP06
        {
            get { return fPROP06; }
            set { SetPropertyValue<string>(nameof(PROP06), ref fPROP06, value); }
        }
        string fPROP07;
        [DbType("VARCHAR2(64 BYTE)")]
        public string PROP07
        {
            get { return fPROP07; }
            set { SetPropertyValue<string>(nameof(PROP07), ref fPROP07, value); }
        }
        string fPROP08;
        [DbType("VARCHAR2(64 BYTE)")]
        public string PROP08
        {
            get { return fPROP08; }
            set { SetPropertyValue<string>(nameof(PROP08), ref fPROP08, value); }
        }
        string fPROP09;
        [DbType("VARCHAR2(64 BYTE)")]
        public string PROP09
        {
            get { return fPROP09; }
            set { SetPropertyValue<string>(nameof(PROP09), ref fPROP09, value); }
        }
        string fPROP10;
        [DbType("VARCHAR2(64 BYTE)")]
        public string PROP10
        {
            get { return fPROP10; }
            set { SetPropertyValue<string>(nameof(PROP10), ref fPROP10, value); }
        }
        string fIN_USER;
        [DbType("VARCHAR2(20 BYTE)")]
        public string IN_USER
        {
            get { return fIN_USER; }
            set { SetPropertyValue<string>(nameof(IN_USER), ref fIN_USER, value); }
        }
        DateTime fIN_DATE;
        [ColumnDbDefaultValue("SYSDATE")]
        public DateTime IN_DATE
        {
            get { return fIN_DATE; }
            set { SetPropertyValue<DateTime>(nameof(IN_DATE), ref fIN_DATE, value); }
        }
        string fIN_IP;
        [DbType("VARCHAR2(15 BYTE)")]
        public string IN_IP
        {
            get { return fIN_IP; }
            set { SetPropertyValue<string>(nameof(IN_IP), ref fIN_IP, value); }
        }
        string fIN_PID;
        [DbType("VARCHAR2(50 BYTE)")]
        public string IN_PID
        {
            get { return fIN_PID; }
            set { SetPropertyValue<string>(nameof(IN_PID), ref fIN_PID, value); }
        }
        string fUP_USER;
        [DbType("VARCHAR2(20 BYTE)")]
        public string UP_USER
        {
            get { return fUP_USER; }
            set { SetPropertyValue<string>(nameof(UP_USER), ref fUP_USER, value); }
        }
        DateTime fUP_DATE;
        public DateTime UP_DATE
        {
            get { return fUP_DATE; }
            set { SetPropertyValue<DateTime>(nameof(UP_DATE), ref fUP_DATE, value); }
        }
        string fUP_IP;
        [DbType("VARCHAR2(15 BYTE)")]
        public string UP_IP
        {
            get { return fUP_IP; }
            set { SetPropertyValue<string>(nameof(UP_IP), ref fUP_IP, value); }
        }
        string fUP_PID;
        [DbType("VARCHAR2(50 BYTE)")]
        public string UP_PID
        {
            get { return fUP_PID; }
            set { SetPropertyValue<string>(nameof(UP_PID), ref fUP_PID, value); }
        }
        public struct CompoundKey1Struct
        {
            [DbType("VARCHAR2(128 BYTE)")]
            [Persistent("COMPANY_NO")]
            public string COMPANY_NO { get; set; }
            [DbType("VARCHAR2(12 BYTE)")]
            [Persistent("CASE_NO")]
            public string CASE_NO { get; set; }
            [DbType("VARCHAR2(32 BYTE)")]
            [Persistent("PROJECT_NO")]
            public string PROJECT_NO { get; set; }
            [DbType("VARCHAR2(32 BYTE)")]
            [Persistent("ORDER_NO")]
            public string ORDER_NO { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
