//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace KShiftSmartPortal.Database
{

    public partial class STD_PERSONNEL_INFO : XPLiteObject
    {
        string fEMP_NAME;
        [DbType("VARCHAR2(128 BYTE)")]
        public string EMP_NAME
        {
            get { return fEMP_NAME; }
            set { SetPropertyValue<string>(nameof(EMP_NAME), ref fEMP_NAME, value); }
        }
        string fUSER_ID;
        [DbType("VARCHAR2(32 BYTE)")]
        public string USER_ID
        {
            get { return fUSER_ID; }
            set { SetPropertyValue<string>(nameof(USER_ID), ref fUSER_ID, value); }
        }
        string fUSER_NAME;
        [DbType("VARCHAR2(128 BYTE)")]
        public string USER_NAME
        {
            get { return fUSER_NAME; }
            set { SetPropertyValue<string>(nameof(USER_NAME), ref fUSER_NAME, value); }
        }
        string fORG_NO;
        [DbType("VARCHAR2(128 BYTE)")]
        public string ORG_NO
        {
            get { return fORG_NO; }
            set { SetPropertyValue<string>(nameof(ORG_NO), ref fORG_NO, value); }
        }
        string fEMAIL_ADDR;
        [DbType("VARCHAR2(64 BYTE)")]
        public string EMAIL_ADDR
        {
            get { return fEMAIL_ADDR; }
            set { SetPropertyValue<string>(nameof(EMAIL_ADDR), ref fEMAIL_ADDR, value); }
        }
        string fJOB;
        [DbType("VARCHAR2(32 BYTE)")]
        public string JOB
        {
            get { return fJOB; }
            set { SetPropertyValue<string>(nameof(JOB), ref fJOB, value); }
        }
        string fJOB_STATUS;
        [DbType("VARCHAR2(128 BYTE)")]
        public string JOB_STATUS
        {
            get { return fJOB_STATUS; }
            set { SetPropertyValue<string>(nameof(JOB_STATUS), ref fJOB_STATUS, value); }
        }
        string fRANK;
        [DbType("VARCHAR2(32 BYTE)")]
        public string RANK
        {
            get { return fRANK; }
            set { SetPropertyValue<string>(nameof(RANK), ref fRANK, value); }
        }
        string fJOB_POS;
        [DbType("VARCHAR2(32 BYTE)")]
        public string JOB_POS
        {
            get { return fJOB_POS; }
            set { SetPropertyValue<string>(nameof(JOB_POS), ref fJOB_POS, value); }
        }
        string fJOB_DEGREE;
        [DbType("VARCHAR2(32 BYTE)")]
        public string JOB_DEGREE
        {
            get { return fJOB_DEGREE; }
            set { SetPropertyValue<string>(nameof(JOB_DEGREE), ref fJOB_DEGREE, value); }
        }
        string fTEL_NO;
        [DbType("VARCHAR2(32 BYTE)")]
        public string TEL_NO
        {
            get { return fTEL_NO; }
            set { SetPropertyValue<string>(nameof(TEL_NO), ref fTEL_NO, value); }
        }
        string fFAX_NO;
        [DbType("VARCHAR2(32 BYTE)")]
        public string FAX_NO
        {
            get { return fFAX_NO; }
            set { SetPropertyValue<string>(nameof(FAX_NO), ref fFAX_NO, value); }
        }
        string fREPRESENTATIVES;
        [DbType("VARCHAR2(32 BYTE)")]
        public string REPRESENTATIVES
        {
            get { return fREPRESENTATIVES; }
            set { SetPropertyValue<string>(nameof(REPRESENTATIVES), ref fREPRESENTATIVES, value); }
        }
        string fLOCATION;
        [DbType("VARCHAR2(128 BYTE)")]
        public string LOCATION
        {
            get { return fLOCATION; }
            set { SetPropertyValue<string>(nameof(LOCATION), ref fLOCATION, value); }
        }
        string fENTRY_YEAR;
        [DbType("VARCHAR2(32 BYTE)")]
        public string ENTRY_YEAR
        {
            get { return fENTRY_YEAR; }
            set { SetPropertyValue<string>(nameof(ENTRY_YEAR), ref fENTRY_YEAR, value); }
        }
        string fRE_ENTRY_YEAR;
        [DbType("VARCHAR2(32 BYTE)")]
        public string RE_ENTRY_YEAR
        {
            get { return fRE_ENTRY_YEAR; }
            set { SetPropertyValue<string>(nameof(RE_ENTRY_YEAR), ref fRE_ENTRY_YEAR, value); }
        }
        string fRMK;
        [DbType("VARCHAR2(2000 BYTE)")]
        public string RMK
        {
            get { return fRMK; }
            set { SetPropertyValue<string>(nameof(RMK), ref fRMK, value); }
        }
        string fTAG1;
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG1
        {
            get { return fTAG1; }
            set { SetPropertyValue<string>(nameof(TAG1), ref fTAG1, value); }
        }
        string fTAG2;
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG2
        {
            get { return fTAG2; }
            set { SetPropertyValue<string>(nameof(TAG2), ref fTAG2, value); }
        }
        string fTAG3;
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG3
        {
            get { return fTAG3; }
            set { SetPropertyValue<string>(nameof(TAG3), ref fTAG3, value); }
        }
        string fTAG4;
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG4
        {
            get { return fTAG4; }
            set { SetPropertyValue<string>(nameof(TAG4), ref fTAG4, value); }
        }
        string fTAG5;
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG5
        {
            get { return fTAG5; }
            set { SetPropertyValue<string>(nameof(TAG5), ref fTAG5, value); }
        }
        string fPROP1;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP1
        {
            get { return fPROP1; }
            set { SetPropertyValue<string>(nameof(PROP1), ref fPROP1, value); }
        }
        string fPROP2;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP2
        {
            get { return fPROP2; }
            set { SetPropertyValue<string>(nameof(PROP2), ref fPROP2, value); }
        }
        string fPROP3;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP3
        {
            get { return fPROP3; }
            set { SetPropertyValue<string>(nameof(PROP3), ref fPROP3, value); }
        }
        string fPROP4;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP4
        {
            get { return fPROP4; }
            set { SetPropertyValue<string>(nameof(PROP4), ref fPROP4, value); }
        }
        string fPROP5;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP5
        {
            get { return fPROP5; }
            set { SetPropertyValue<string>(nameof(PROP5), ref fPROP5, value); }
        }
        string fPROP6;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP6
        {
            get { return fPROP6; }
            set { SetPropertyValue<string>(nameof(PROP6), ref fPROP6, value); }
        }
        string fPROP7;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP7
        {
            get { return fPROP7; }
            set { SetPropertyValue<string>(nameof(PROP7), ref fPROP7, value); }
        }
        string fPROP8;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP8
        {
            get { return fPROP8; }
            set { SetPropertyValue<string>(nameof(PROP8), ref fPROP8, value); }
        }
        string fPROP9;
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP9
        {
            get { return fPROP9; }
            set { SetPropertyValue<string>(nameof(PROP9), ref fPROP9, value); }
        }
        string fIN_USER;
        [DbType("VARCHAR2(20 BYTE)")]
        public string IN_USER
        {
            get { return fIN_USER; }
            set { SetPropertyValue<string>(nameof(IN_USER), ref fIN_USER, value); }
        }
        DateTime fIN_DATE;
        [ColumnDbDefaultValue("SYSDATE")]
        public DateTime IN_DATE
        {
            get { return fIN_DATE; }
            set { SetPropertyValue<DateTime>(nameof(IN_DATE), ref fIN_DATE, value); }
        }
        string fIN_IP;
        [DbType("VARCHAR2(15 BYTE)")]
        public string IN_IP
        {
            get { return fIN_IP; }
            set { SetPropertyValue<string>(nameof(IN_IP), ref fIN_IP, value); }
        }
        string fIN_PID;
        [DbType("VARCHAR2(50 BYTE)")]
        public string IN_PID
        {
            get { return fIN_PID; }
            set { SetPropertyValue<string>(nameof(IN_PID), ref fIN_PID, value); }
        }
        string fUP_USER;
        [DbType("VARCHAR2(20 BYTE)")]
        public string UP_USER
        {
            get { return fUP_USER; }
            set { SetPropertyValue<string>(nameof(UP_USER), ref fUP_USER, value); }
        }
        DateTime fUP_DATE;
        public DateTime UP_DATE
        {
            get { return fUP_DATE; }
            set { SetPropertyValue<DateTime>(nameof(UP_DATE), ref fUP_DATE, value); }
        }
        string fUP_IP;
        [DbType("VARCHAR2(15 BYTE)")]
        public string UP_IP
        {
            get { return fUP_IP; }
            set { SetPropertyValue<string>(nameof(UP_IP), ref fUP_IP, value); }
        }
        string fUP_PID;
        [DbType("VARCHAR2(50 BYTE)")]
        public string UP_PID
        {
            get { return fUP_PID; }
            set { SetPropertyValue<string>(nameof(UP_PID), ref fUP_PID, value); }
        }
        decimal fVAL01;
        public decimal VAL01
        {
            get { return fVAL01; }
            set { SetPropertyValue<decimal>(nameof(VAL01), ref fVAL01, value); }
        }
        decimal fVAL02;
        public decimal VAL02
        {
            get { return fVAL02; }
            set { SetPropertyValue<decimal>(nameof(VAL02), ref fVAL02, value); }
        }
        decimal fVAL03;
        public decimal VAL03
        {
            get { return fVAL03; }
            set { SetPropertyValue<decimal>(nameof(VAL03), ref fVAL03, value); }
        }
        decimal fVAL04;
        public decimal VAL04
        {
            get { return fVAL04; }
            set { SetPropertyValue<decimal>(nameof(VAL04), ref fVAL04, value); }
        }
        decimal fVAL05;
        public decimal VAL05
        {
            get { return fVAL05; }
            set { SetPropertyValue<decimal>(nameof(VAL05), ref fVAL05, value); }
        }
        public struct CompoundKey1Struct
        {
            [DbType("VARCHAR2(128 BYTE)")]
            [Persistent("COMPANY_NO")]
            public string COMPANY_NO { get; set; }
            [DbType("VARCHAR2(32 BYTE)")]
            [Persistent("EMP_NO")]
            public string EMP_NO { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
