//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace KShiftSmartPortal.Database
{

    public partial class SCM_CONTRACT_DETAIL : XPLiteObject
    {
        string fACT_NO;
        [DbType("VARCHAR2(32 BYTE)")]
        public string ACT_NO
        {
            get { return fACT_NO; }
            set { SetPropertyValue<string>(nameof(ACT_NO), ref fACT_NO, value); }
        }
        string fOWNER_DEPT;
        [DbType("VARCHAR2(64 BYTE)")]
        public string OWNER_DEPT
        {
            get { return fOWNER_DEPT; }
            set { SetPropertyValue<string>(nameof(OWNER_DEPT), ref fOWNER_DEPT, value); }
        }
        string fMAIN_CONTRACTOR;
        [DbType("VARCHAR2(64 BYTE)")]
        public string MAIN_CONTRACTOR
        {
            get { return fMAIN_CONTRACTOR; }
            set { SetPropertyValue<string>(nameof(MAIN_CONTRACTOR), ref fMAIN_CONTRACTOR, value); }
        }
        string fSUB_CONTRACTOR;
        [DbType("VARCHAR2(64 BYTE)")]
        public string SUB_CONTRACTOR
        {
            get { return fSUB_CONTRACTOR; }
            set { SetPropertyValue<string>(nameof(SUB_CONTRACTOR), ref fSUB_CONTRACTOR, value); }
        }
        string fSUB_CONTRACTOR2;
        [DbType("VARCHAR2(64 BYTE)")]
        public string SUB_CONTRACTOR2
        {
            get { return fSUB_CONTRACTOR2; }
            set { SetPropertyValue<string>(nameof(SUB_CONTRACTOR2), ref fSUB_CONTRACTOR2, value); }
        }
        string fSUB_CONTRACTOR2_DESC;
        [DbType("VARCHAR2(64 BYTE)")]
        public string SUB_CONTRACTOR2_DESC
        {
            get { return fSUB_CONTRACTOR2_DESC; }
            set { SetPropertyValue<string>(nameof(SUB_CONTRACTOR2_DESC), ref fSUB_CONTRACTOR2_DESC, value); }
        }
        string fMS_NO;
        [DbType("VARCHAR2(32 BYTE)")]
        public string MS_NO
        {
            get { return fMS_NO; }
            set { SetPropertyValue<string>(nameof(MS_NO), ref fMS_NO, value); }
        }
        DateTime fMS_DT;
        public DateTime MS_DT
        {
            get { return fMS_DT; }
            set { SetPropertyValue<DateTime>(nameof(MS_DT), ref fMS_DT, value); }
        }
        string fMS_CONTRACTOR;
        [DbType("VARCHAR2(64 BYTE)")]
        public string MS_CONTRACTOR
        {
            get { return fMS_CONTRACTOR; }
            set { SetPropertyValue<string>(nameof(MS_CONTRACTOR), ref fMS_CONTRACTOR, value); }
        }
        string fPAINT_MS_NO;
        [DbType("VARCHAR2(32 BYTE)")]
        public string PAINT_MS_NO
        {
            get { return fPAINT_MS_NO; }
            set { SetPropertyValue<string>(nameof(PAINT_MS_NO), ref fPAINT_MS_NO, value); }
        }
        DateTime fPAINT_MS_DT;
        public DateTime PAINT_MS_DT
        {
            get { return fPAINT_MS_DT; }
            set { SetPropertyValue<DateTime>(nameof(PAINT_MS_DT), ref fPAINT_MS_DT, value); }
        }
        string fPAINT_MS_CONTRACTOR;
        [DbType("VARCHAR2(64 BYTE)")]
        public string PAINT_MS_CONTRACTOR
        {
            get { return fPAINT_MS_CONTRACTOR; }
            set { SetPropertyValue<string>(nameof(PAINT_MS_CONTRACTOR), ref fPAINT_MS_CONTRACTOR, value); }
        }
        DateTime fDRAWING_DT;
        public DateTime DRAWING_DT
        {
            get { return fDRAWING_DT; }
            set { SetPropertyValue<DateTime>(nameof(DRAWING_DT), ref fDRAWING_DT, value); }
        }
        DateTime fDRAWING_INIT_DT;
        public DateTime DRAWING_INIT_DT
        {
            get { return fDRAWING_INIT_DT; }
            set { SetPropertyValue<DateTime>(nameof(DRAWING_INIT_DT), ref fDRAWING_INIT_DT, value); }
        }
        DateTime fMAT_LOG_REQ_DT;
        public DateTime MAT_LOG_REQ_DT
        {
            get { return fMAT_LOG_REQ_DT; }
            set { SetPropertyValue<DateTime>(nameof(MAT_LOG_REQ_DT), ref fMAT_LOG_REQ_DT, value); }
        }
        DateTime fMAT_LOG_DT;
        public DateTime MAT_LOG_DT
        {
            get { return fMAT_LOG_DT; }
            set { SetPropertyValue<DateTime>(nameof(MAT_LOG_DT), ref fMAT_LOG_DT, value); }
        }
        string fMAT_LOG_REQ_NO;
        [DbType("VARCHAR2(32 BYTE)")]
        public string MAT_LOG_REQ_NO
        {
            get { return fMAT_LOG_REQ_NO; }
            set { SetPropertyValue<string>(nameof(MAT_LOG_REQ_NO), ref fMAT_LOG_REQ_NO, value); }
        }
        string fMAT_LOG_POS_NM;
        [DbType("VARCHAR2(32 BYTE)")]
        public string MAT_LOG_POS_NM
        {
            get { return fMAT_LOG_POS_NM; }
            set { SetPropertyValue<string>(nameof(MAT_LOG_POS_NM), ref fMAT_LOG_POS_NM, value); }
        }
        string fMAT_LOG_REQ_PER;
        [DbType("VARCHAR2(32 BYTE)")]
        public string MAT_LOG_REQ_PER
        {
            get { return fMAT_LOG_REQ_PER; }
            set { SetPropertyValue<string>(nameof(MAT_LOG_REQ_PER), ref fMAT_LOG_REQ_PER, value); }
        }
        string fMAT_LOG_REQ_DEPT;
        [DbType("VARCHAR2(32 BYTE)")]
        public string MAT_LOG_REQ_DEPT
        {
            get { return fMAT_LOG_REQ_DEPT; }
            set { SetPropertyValue<string>(nameof(MAT_LOG_REQ_DEPT), ref fMAT_LOG_REQ_DEPT, value); }
        }
        string fMAT_LOG_REQ_TEL;
        [DbType("VARCHAR2(32 BYTE)")]
        public string MAT_LOG_REQ_TEL
        {
            get { return fMAT_LOG_REQ_TEL; }
            set { SetPropertyValue<string>(nameof(MAT_LOG_REQ_TEL), ref fMAT_LOG_REQ_TEL, value); }
        }
        string fMAT_LOG_PER;
        [DbType("VARCHAR2(32 BYTE)")]
        public string MAT_LOG_PER
        {
            get { return fMAT_LOG_PER; }
            set { SetPropertyValue<string>(nameof(MAT_LOG_PER), ref fMAT_LOG_PER, value); }
        }
        string fMPPL_PROJ;
        [DbType("VARCHAR2(32 BYTE)")]
        public string MPPL_PROJ
        {
            get { return fMPPL_PROJ; }
            set { SetPropertyValue<string>(nameof(MPPL_PROJ), ref fMPPL_PROJ, value); }
        }
        string fMPPL_NO;
        [DbType("VARCHAR2(32 BYTE)")]
        public string MPPL_NO
        {
            get { return fMPPL_NO; }
            set { SetPropertyValue<string>(nameof(MPPL_NO), ref fMPPL_NO, value); }
        }
        string fMPPL_SEQ;
        [DbType("VARCHAR2(32 BYTE)")]
        public string MPPL_SEQ
        {
            get { return fMPPL_SEQ; }
            set { SetPropertyValue<string>(nameof(MPPL_SEQ), ref fMPPL_SEQ, value); }
        }
        DateTime fMP_RES_DT;
        public DateTime MP_RES_DT
        {
            get { return fMP_RES_DT; }
            set { SetPropertyValue<DateTime>(nameof(MP_RES_DT), ref fMP_RES_DT, value); }
        }
        DateTime fMAKING_DT;
        public DateTime MAKING_DT
        {
            get { return fMAKING_DT; }
            set { SetPropertyValue<DateTime>(nameof(MAKING_DT), ref fMAKING_DT, value); }
        }
        DateTime fMAKING_RES_DT;
        public DateTime MAKING_RES_DT
        {
            get { return fMAKING_RES_DT; }
            set { SetPropertyValue<DateTime>(nameof(MAKING_RES_DT), ref fMAKING_RES_DT, value); }
        }
        DateTime fPAINTING_DT;
        public DateTime PAINTING_DT
        {
            get { return fPAINTING_DT; }
            set { SetPropertyValue<DateTime>(nameof(PAINTING_DT), ref fPAINTING_DT, value); }
        }
        DateTime fPAINTING_RES_DT;
        public DateTime PAINTING_RES_DT
        {
            get { return fPAINTING_RES_DT; }
            set { SetPropertyValue<DateTime>(nameof(PAINTING_RES_DT), ref fPAINTING_RES_DT, value); }
        }
        DateTime fINSPECTION_DT;
        public DateTime INSPECTION_DT
        {
            get { return fINSPECTION_DT; }
            set { SetPropertyValue<DateTime>(nameof(INSPECTION_DT), ref fINSPECTION_DT, value); }
        }
        DateTime fINSPECTION_RES_DT;
        public DateTime INSPECTION_RES_DT
        {
            get { return fINSPECTION_RES_DT; }
            set { SetPropertyValue<DateTime>(nameof(INSPECTION_RES_DT), ref fINSPECTION_RES_DT, value); }
        }
        string fTAG1;
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG1
        {
            get { return fTAG1; }
            set { SetPropertyValue<string>(nameof(TAG1), ref fTAG1, value); }
        }
        string fTAG2;
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG2
        {
            get { return fTAG2; }
            set { SetPropertyValue<string>(nameof(TAG2), ref fTAG2, value); }
        }
        string fTAG3;
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG3
        {
            get { return fTAG3; }
            set { SetPropertyValue<string>(nameof(TAG3), ref fTAG3, value); }
        }
        string fTAG4;
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG4
        {
            get { return fTAG4; }
            set { SetPropertyValue<string>(nameof(TAG4), ref fTAG4, value); }
        }
        string fTAG5;
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG5
        {
            get { return fTAG5; }
            set { SetPropertyValue<string>(nameof(TAG5), ref fTAG5, value); }
        }
        string fIN_USER;
        [DbType("VARCHAR2(20 BYTE)")]
        public string IN_USER
        {
            get { return fIN_USER; }
            set { SetPropertyValue<string>(nameof(IN_USER), ref fIN_USER, value); }
        }
        DateTime fIN_DATE;
        [ColumnDbDefaultValue("SYSDATE")]
        public DateTime IN_DATE
        {
            get { return fIN_DATE; }
            set { SetPropertyValue<DateTime>(nameof(IN_DATE), ref fIN_DATE, value); }
        }
        string fIN_IP;
        [DbType("VARCHAR2(15 BYTE)")]
        public string IN_IP
        {
            get { return fIN_IP; }
            set { SetPropertyValue<string>(nameof(IN_IP), ref fIN_IP, value); }
        }
        string fIN_PID;
        [DbType("VARCHAR2(50 BYTE)")]
        public string IN_PID
        {
            get { return fIN_PID; }
            set { SetPropertyValue<string>(nameof(IN_PID), ref fIN_PID, value); }
        }
        string fUP_USER;
        [DbType("VARCHAR2(20 BYTE)")]
        public string UP_USER
        {
            get { return fUP_USER; }
            set { SetPropertyValue<string>(nameof(UP_USER), ref fUP_USER, value); }
        }
        DateTime fUP_DATE;
        public DateTime UP_DATE
        {
            get { return fUP_DATE; }
            set { SetPropertyValue<DateTime>(nameof(UP_DATE), ref fUP_DATE, value); }
        }
        string fUP_IP;
        [DbType("VARCHAR2(15 BYTE)")]
        public string UP_IP
        {
            get { return fUP_IP; }
            set { SetPropertyValue<string>(nameof(UP_IP), ref fUP_IP, value); }
        }
        string fUP_PID;
        [DbType("VARCHAR2(50 BYTE)")]
        public string UP_PID
        {
            get { return fUP_PID; }
            set { SetPropertyValue<string>(nameof(UP_PID), ref fUP_PID, value); }
        }
        public struct CompoundKey1Struct
        {
            [DbType("VARCHAR2(12 BYTE)")]
            [Persistent("CASE_NO")]
            public string CASE_NO { get; set; }
            [DbType("VARCHAR2(128 BYTE)")]
            [Persistent("COMPANY_NO")]
            public string COMPANY_NO { get; set; }
            [DbType("VARCHAR2(32 BYTE)")]
            [Persistent("CONTRACT_ID")]
            public string CONTRACT_ID { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
