//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace KShiftSmartPortal.Database
{

    public partial class SCM_CONTRACT_MASTER : XPLiteObject
    {
        string fCONTRACT_NAME;
        [Size(128)]
        [DbType("VARCHAR2(128 BYTE)")]
        public string CONTRACT_NAME
        {
            get { return fCONTRACT_NAME; }
            set { SetPropertyValue<string>(nameof(CONTRACT_NAME), ref fCONTRACT_NAME, value); }
        }
        string fCONTRACT_CATEGORY;
        [Size(32)]
        [ColumnDbDefaultValue("'ING'")]
        [DbType("VARCHAR2(32 BYTE)")]
        public string CONTRACT_CATEGORY
        {
            get { return fCONTRACT_CATEGORY; }
            set { SetPropertyValue<string>(nameof(CONTRACT_CATEGORY), ref fCONTRACT_CATEGORY, value); }
        }
        string fCONTRACT_TYPE;
        [Size(12)]
        [ColumnDbDefaultValue("'CONTRACTED'")]
        [DbType("VARCHAR2(12 BYTE)")]
        public string CONTRACT_TYPE
        {
            get { return fCONTRACT_TYPE; }
            set { SetPropertyValue<string>(nameof(CONTRACT_TYPE), ref fCONTRACT_TYPE, value); }
        }
        string fCONTRACT_NO;
        [Size(32)]
        [DbType("VARCHAR2(32 BYTE)")]
        public string CONTRACT_NO
        {
            get { return fCONTRACT_NO; }
            set { SetPropertyValue<string>(nameof(CONTRACT_NO), ref fCONTRACT_NO, value); }
        }
        string fPOR_NO;
        [Size(32)]
        [DbType("VARCHAR2(32 BYTE)")]
        public string POR_NO
        {
            get { return fPOR_NO; }
            set { SetPropertyValue<string>(nameof(POR_NO), ref fPOR_NO, value); }
        }
        string fSEQ_NO;
        [Size(32)]
        [DbType("VARCHAR2(32 BYTE)")]
        public string SEQ_NO
        {
            get { return fSEQ_NO; }
            set { SetPropertyValue<string>(nameof(SEQ_NO), ref fSEQ_NO, value); }
        }
        string fPROJECT_NO;
        [Size(32)]
        [DbType("VARCHAR2(32 BYTE)")]
        public string PROJECT_NO
        {
            get { return fPROJECT_NO; }
            set { SetPropertyValue<string>(nameof(PROJECT_NO), ref fPROJECT_NO, value); }
        }
        string fBLOCK_NO;
        [Size(32)]
        [DbType("VARCHAR2(32 BYTE)")]
        public string BLOCK_NO
        {
            get { return fBLOCK_NO; }
            set { SetPropertyValue<string>(nameof(BLOCK_NO), ref fBLOCK_NO, value); }
        }
        string fMARK_NO;
        [Size(32)]
        [DbType("VARCHAR2(32 BYTE)")]
        public string MARK_NO
        {
            get { return fMARK_NO; }
            set { SetPropertyValue<string>(nameof(MARK_NO), ref fMARK_NO, value); }
        }
        string fPRODUCT_DESC;
        [Size(252)]
        [DbType("VARCHAR2(252 BYTE)")]
        public string PRODUCT_DESC
        {
            get { return fPRODUCT_DESC; }
            set { SetPropertyValue<string>(nameof(PRODUCT_DESC), ref fPRODUCT_DESC, value); }
        }
        string fPRODUCT_TYPE;
        [Size(128)]
        [DbType("VARCHAR2(128 BYTE)")]
        public string PRODUCT_TYPE
        {
            get { return fPRODUCT_TYPE; }
            set { SetPropertyValue<string>(nameof(PRODUCT_TYPE), ref fPRODUCT_TYPE, value); }
        }
        bool fCNTR_STATUS;
        [ColumnDbDefaultValue("0")]
        public bool CNTR_STATUS
        {
            get { return fCNTR_STATUS; }
            set { SetPropertyValue<bool>(nameof(CNTR_STATUS), ref fCNTR_STATUS, value); }
        }
        DateTime fPOR_DT;
        public DateTime POR_DT
        {
            get { return fPOR_DT; }
            set { SetPropertyValue<DateTime>(nameof(POR_DT), ref fPOR_DT, value); }
        }
        DateTime fCNTR_DT;
        public DateTime CNTR_DT
        {
            get { return fCNTR_DT; }
            set { SetPropertyValue<DateTime>(nameof(CNTR_DT), ref fCNTR_DT, value); }
        }
        DateTime fCNTR_INIT_DT;
        public DateTime CNTR_INIT_DT
        {
            get { return fCNTR_INIT_DT; }
            set { SetPropertyValue<DateTime>(nameof(CNTR_INIT_DT), ref fCNTR_INIT_DT, value); }
        }
        DateTime fMP_DT;
        public DateTime MP_DT
        {
            get { return fMP_DT; }
            set { SetPropertyValue<DateTime>(nameof(MP_DT), ref fMP_DT, value); }
        }
        DateTime fMP_INIT_DT;
        public DateTime MP_INIT_DT
        {
            get { return fMP_INIT_DT; }
            set { SetPropertyValue<DateTime>(nameof(MP_INIT_DT), ref fMP_INIT_DT, value); }
        }
        int fCNTR_EA;
        public int CNTR_EA
        {
            get { return fCNTR_EA; }
            set { SetPropertyValue<int>(nameof(CNTR_EA), ref fCNTR_EA, value); }
        }
        decimal fCNTR_WGT;
        public decimal CNTR_WGT
        {
            get { return fCNTR_WGT; }
            set { SetPropertyValue<decimal>(nameof(CNTR_WGT), ref fCNTR_WGT, value); }
        }
        decimal fCNTR_PIECE_WGT;
        public decimal CNTR_PIECE_WGT
        {
            get { return fCNTR_PIECE_WGT; }
            set { SetPropertyValue<decimal>(nameof(CNTR_PIECE_WGT), ref fCNTR_PIECE_WGT, value); }
        }
        string fOWNER;
        [Size(36)]
        [DbType("VARCHAR2(36 BYTE)")]
        public string OWNER
        {
            get { return fOWNER; }
            set { SetPropertyValue<string>(nameof(OWNER), ref fOWNER, value); }
        }
        string fSTD_CASE_NO;
        [Size(12)]
        [ColumnDbDefaultValue("'MASTER'")]
        [DbType("VARCHAR2(12 BYTE)")]
        public string STD_CASE_NO
        {
            get { return fSTD_CASE_NO; }
            set { SetPropertyValue<string>(nameof(STD_CASE_NO), ref fSTD_CASE_NO, value); }
        }
        string fSTD_CONTRACT_ID;
        [Size(32)]
        [DbType("VARCHAR2(32 BYTE)")]
        public string STD_CONTRACT_ID
        {
            get { return fSTD_CONTRACT_ID; }
            set { SetPropertyValue<string>(nameof(STD_CONTRACT_ID), ref fSTD_CONTRACT_ID, value); }
        }
        DateTime fEST_ST_DT;
        public DateTime EST_ST_DT
        {
            get { return fEST_ST_DT; }
            set { SetPropertyValue<DateTime>(nameof(EST_ST_DT), ref fEST_ST_DT, value); }
        }
        DateTime fEST_FI_DT;
        public DateTime EST_FI_DT
        {
            get { return fEST_FI_DT; }
            set { SetPropertyValue<DateTime>(nameof(EST_FI_DT), ref fEST_FI_DT, value); }
        }
        DateTime fPLAN_ST_DT;
        public DateTime PLAN_ST_DT
        {
            get { return fPLAN_ST_DT; }
            set { SetPropertyValue<DateTime>(nameof(PLAN_ST_DT), ref fPLAN_ST_DT, value); }
        }
        DateTime fPLAN_FI_DT;
        public DateTime PLAN_FI_DT
        {
            get { return fPLAN_FI_DT; }
            set { SetPropertyValue<DateTime>(nameof(PLAN_FI_DT), ref fPLAN_FI_DT, value); }
        }
        DateTime fRESULT_ST_DT;
        public DateTime RESULT_ST_DT
        {
            get { return fRESULT_ST_DT; }
            set { SetPropertyValue<DateTime>(nameof(RESULT_ST_DT), ref fRESULT_ST_DT, value); }
        }
        DateTime fRESULT_FI_DT;
        public DateTime RESULT_FI_DT
        {
            get { return fRESULT_FI_DT; }
            set { SetPropertyValue<DateTime>(nameof(RESULT_FI_DT), ref fRESULT_FI_DT, value); }
        }
        string fRMK;
        [Size(128)]
        [DbType("VARCHAR2(128 BYTE)")]
        public string RMK
        {
            get { return fRMK; }
            set { SetPropertyValue<string>(nameof(RMK), ref fRMK, value); }
        }
        string fTAG1;
        [Size(128)]
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG1
        {
            get { return fTAG1; }
            set { SetPropertyValue<string>(nameof(TAG1), ref fTAG1, value); }
        }
        string fTAG2;
        [Size(128)]
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG2
        {
            get { return fTAG2; }
            set { SetPropertyValue<string>(nameof(TAG2), ref fTAG2, value); }
        }
        string fTAG3;
        [Size(128)]
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG3
        {
            get { return fTAG3; }
            set { SetPropertyValue<string>(nameof(TAG3), ref fTAG3, value); }
        }
        string fTAG4;
        [Size(128)]
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG4
        {
            get { return fTAG4; }
            set { SetPropertyValue<string>(nameof(TAG4), ref fTAG4, value); }
        }
        string fTAG5;
        [Size(128)]
        [DbType("VARCHAR2(128 BYTE)")]
        public string TAG5
        {
            get { return fTAG5; }
            set { SetPropertyValue<string>(nameof(TAG5), ref fTAG5, value); }
        }
        string fPROP1;
        [Size(128)]
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP1
        {
            get { return fPROP1; }
            set { SetPropertyValue<string>(nameof(PROP1), ref fPROP1, value); }
        }
        string fPROP2;
        [Size(128)]
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP2
        {
            get { return fPROP2; }
            set { SetPropertyValue<string>(nameof(PROP2), ref fPROP2, value); }
        }
        string fPROP3;
        [Size(128)]
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP3
        {
            get { return fPROP3; }
            set { SetPropertyValue<string>(nameof(PROP3), ref fPROP3, value); }
        }
        string fPROP4;
        [Size(128)]
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP4
        {
            get { return fPROP4; }
            set { SetPropertyValue<string>(nameof(PROP4), ref fPROP4, value); }
        }
        string fPROP5;
        [Size(128)]
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP5
        {
            get { return fPROP5; }
            set { SetPropertyValue<string>(nameof(PROP5), ref fPROP5, value); }
        }
        string fPROP6;
        [Size(128)]
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP6
        {
            get { return fPROP6; }
            set { SetPropertyValue<string>(nameof(PROP6), ref fPROP6, value); }
        }
        string fPROP7;
        [Size(128)]
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP7
        {
            get { return fPROP7; }
            set { SetPropertyValue<string>(nameof(PROP7), ref fPROP7, value); }
        }
        string fPROP8;
        [Size(128)]
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP8
        {
            get { return fPROP8; }
            set { SetPropertyValue<string>(nameof(PROP8), ref fPROP8, value); }
        }
        string fPROP9;
        [Size(128)]
        [DbType("VARCHAR2(128 BYTE)")]
        public string PROP9
        {
            get { return fPROP9; }
            set { SetPropertyValue<string>(nameof(PROP9), ref fPROP9, value); }
        }
        string fIN_USER;
        [Size(20)]
        [DbType("VARCHAR2(20 BYTE)")]
        public string IN_USER
        {
            get { return fIN_USER; }
            set { SetPropertyValue<string>(nameof(IN_USER), ref fIN_USER, value); }
        }
        DateTime fIN_DATE;
        [ColumnDbDefaultValue("SYSDATE")]
        public DateTime IN_DATE
        {
            get { return fIN_DATE; }
            set { SetPropertyValue<DateTime>(nameof(IN_DATE), ref fIN_DATE, value); }
        }
        string fIN_IP;
        [Size(15)]
        [DbType("VARCHAR2(15 BYTE)")]
        public string IN_IP
        {
            get { return fIN_IP; }
            set { SetPropertyValue<string>(nameof(IN_IP), ref fIN_IP, value); }
        }
        string fIN_PID;
        [Size(50)]
        [DbType("VARCHAR2(50 BYTE)")]
        public string IN_PID
        {
            get { return fIN_PID; }
            set { SetPropertyValue<string>(nameof(IN_PID), ref fIN_PID, value); }
        }
        string fUP_USER;
        [Size(20)]
        [DbType("VARCHAR2(20 BYTE)")]
        public string UP_USER
        {
            get { return fUP_USER; }
            set { SetPropertyValue<string>(nameof(UP_USER), ref fUP_USER, value); }
        }
        DateTime fUP_DATE;
        public DateTime UP_DATE
        {
            get { return fUP_DATE; }
            set { SetPropertyValue<DateTime>(nameof(UP_DATE), ref fUP_DATE, value); }
        }
        string fUP_IP;
        [Size(15)]
        [DbType("VARCHAR2(15 BYTE)")]
        public string UP_IP
        {
            get { return fUP_IP; }
            set { SetPropertyValue<string>(nameof(UP_IP), ref fUP_IP, value); }
        }
        string fUP_PID;
        [Size(50)]
        [DbType("VARCHAR2(50 BYTE)")]
        public string UP_PID
        {
            get { return fUP_PID; }
            set { SetPropertyValue<string>(nameof(UP_PID), ref fUP_PID, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(12)]
            [DbType("VARCHAR2(12 BYTE)")]
            [Persistent("CASE_NO")]
            public string CASE_NO { get; set; }
            [Size(128)]
            [DbType("VARCHAR2(128 BYTE)")]
            [Persistent("COMPANY_NO")]
            public string COMPANY_NO { get; set; }
            [Size(32)]
            [DbType("VARCHAR2(32 BYTE)")]
            [Persistent("CONTRACT_ID")]
            public string CONTRACT_ID { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
